export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST'
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE'

export const FETCH_ARTICLE_SLUG_REQUEST = 'FETCH_ARTICLE_SLUG_REQUEST'
export const FETCH_ARTICLE_SLUG_SUCCESS = 'FETCH_ARTICLE_SLUG_SUCCESS'
export const FETCH_ARTICLE_SLUG_FAILURE = 'FETCH_ARTICLE_SLUG_FAILURE'

export const FETCH_ARTICLE_SLUG_EDIT_REQUEST = 'FETCH_ARTICLE_SLUG_EDIT_REQUEST'
export const FETCH_ARTICLE_SLUG_EDIT_SUCCESS = 'FETCH_ARTICLE_SLUG_EDIT_SUCCESS'
export const FETCH_ARTICLE_SLUG_EDIT_FAILURE = 'FETCH_ARTICLE_SLUG_EDIT_FAILURE'

export const POST_CREATE_NEW_ACCOUNT = 'POST_CREATE_NEW_ACCOUNT'
export const POST_NEW_ACCOUNT_SUCCESS = 'POST_NEW_ACCOUNT_SUCCESS'
export const POST_NEW_ACCOUNT_FAILURE = 'POST_NEW_ACCOUNT_FAILURE'
export const POST_NEW_ACCOUNT_SERVER_FAIL = 'POST_NEW_ACCOUNT_SERVER_FAIL'

export const POST_LOGIN = 'POST_LOGIN'
export const POST_LOGIN_SUCCES = 'POST_LOGIN_SUCCES'
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE'
export const POST_LOGIN_SERVER_FAIL = 'POST_LOGIN_SERVER_FAIL'
export const LOG_OUT = 'LOG_OUT'

export const PUT_UPDATE_ACCOUNT = 'PUT_UPDATE_ACCOUNT'
export const PUT_UPDATE_ACCOUNT_SUCCESS = 'PUT_UPDATE_ACCOUNT_SUCCESS'
export const PUT_UPDATE_ACCOUNT_FAILURE = 'PUT_UPDATE_ACCOUNT_FAILURE'
export const PUT_UPDATE_ACCOUNT_SERVER_FAIL = 'PUT_UPDATE_ACCOUNT_SERVER_FAIL'

export const GET_CURRENT_USER = 'GET_CURRENT_USER'

export const POST_ARTICLE = 'POST_ARTICLE'
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS'
export const POST_ARTICLE_FAILURE = 'POST_ARTICLE_FAILURE'
export const POST_ARTICLE_SERVER_FAIL = 'POST_ARTICLE_SERVER_FAIL'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE'
export const DELETE_ARTICLE_SERVER_FAIL = 'DELETE_ARTICLE_SERVER_FAIL'

export const PUT_EDIT_ARTICLE = 'PUT_EDIT_ARTICLE'
export const PUT_EDIT_ARTICLE_SUCCES = 'PUT_EDIT_ARTICLE_SUCCES'
export const PUT_EDIT_ARTICLE_FAILURE = 'PUT_EDIT_ARTICLE__FAILURE'
export const PUT_EDIT_ARTICLE_SERVER_FAIL = 'PUT_EDITARTICLE__SERVER_FAIL'

export const POST_FAVORITE_ARTICLE = 'POST_FAVORITE_ARTICLE'
export const DELETE_FAVORITE_ARTICLE = 'DELETE_FAVORITE_ARTICLE'
